---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/health":
    get:
      summary: Health check
      tags:
      - Health
      responses:
        '200':
          description: ok
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
