source "https://rubygems.org"

gem "rails", "~> 8.0"

gem "pg", "~> 1.1"

gem "puma", ">= 6.0"

gem "rack-cors"
gem "devise"
gem "devise-jwt"
gem "pundit"
gem "pagy"
gem "sidekiq"
gem "sidekiq-cron"
gem "lockbox"
gem "lograge"
gem "sentry-rails"
gem "sentry-ruby"
gem "active_model_serializers"
gem "json-schema"
gem "csv"
gem "roo"
gem "roo-xls"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rubocop-rspec", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-factory_bot", require: false
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "rswag"
end

group :test do
  gem "simplecov", require: false
end
