source "https://rubygems.org"

gem "rails", "~> 7.2"

gem "pg"

gem "puma"

gem "rack-cors"

gem "devise"

gem "devise-jwt"

gem "pundit"

gem "pagy"

gem "sidekiq"

gem "sidekiq-cron"

gem "lockbox"

gem "lograge"

gem "sentry-rails"

gem "sentry-ruby"

gem "active_model_serializers"

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "rswag"
end
