name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  api:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: franco
      DB_PASSWORD: franco
    defaults:
      run:
        working-directory: api
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: franco
          POSTGRES_PASSWORD: franco
          POSTGRES_DB: franco_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports: ["6379:6379"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: api
      - name: Setup DB
        run: |
          sudo apt-get update && sudo apt-get install -y libpq-dev
          DB_HOST=localhost DB_PORT=5432 DB_USER=franco DB_PASSWORD=franco bundle exec rails db:prepare RAILS_ENV=test
      - name: RSpec
        run: bundle exec rspec --format progress
      - name: Upload API coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-coverage
          path: api/coverage

  app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Jest
        run: npm run test:ci --silent
      - name: Upload App coverage (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-coverage
          path: app/coverage
